### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "super.admin@cms.com",
    "password": "superadmin@735"
}

### STUDENT SIGNUP
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "name": "Jini Patel",
    "email": "jinipatel@gmail.com",
    "contactNumber": "7852145698",
    "password": "jini@123",
    "branchId": 9,
    "semesterId": 13,
    "yearId": 22
}

### SUPER ADMIN

### CREATE ADMIN
POST http://localhost:5000/api/super-admin/admin
Content-Type: application/json

{
    "name": "Kashish Zalavadi",
    "email": "kashishzalavadi@gmail.com",
    "contactNumber": "9428187521",
    "branchValue": "Chemical Engineering"
}

### GET ALL ADMIN
GET http://localhost:5000/api/super-admin/admin
Content-Type: application/json

### GET ADMIN BY ID
GET http://localhost:5000/api/super-admin/admin/5
Content-Type: application/json

### UPDATE ADMIN
PUT http://localhost:5000/api/super-admin/admin/4
Content-Type: application/json

{
    "name": "Sumit Zala",
    "email": "sumitzala@gmail.com",
    "contactNumber": "942817522"
}

### DELETE ADMIN
DELETE http://localhost:5000/api/super-admin/admin/4

### MY PROFILE 
GET http://localhost:5000/api/super-admin/me
Content-Type: application/json


### ADMIN

### CREATE PROFESSOR
POST http://localhost:5000/api/admin/professor
Content-Type: application/json
# Branch value must be same as Admin Branch
{
  "name": "Sujal Zala",
  "email": "sujalzala66@gmail.com",
  "contactNumber": "9876543210",
  "branchValue": "Chemical Engineering",
  "statusId": 25
}

### GET ALL PROFESSOR
GET http://localhost:5000/api/admin/professor
Content-Type: application/json

### GET PROFESSOR BY ID
GET http://localhost:5000/api/admin/professor/6
Content-Type: application/json

### UPDATE PROFESSOR
PUT http://localhost:5000/api/admin/professor/7
Content-Type: application/json
{
  "name": "Kalpesh P. Kumavat"
}

### DELETE PROFESSOR
DELETE http://localhost:5000/api/admin/professor/7
Content-Type: application/json

### ASSIGN SUBJECT TO PROFESSOR
PUT http://localhost:5000/api/admin/professor/7/subjects
Content-Type: application/json

{
    "subjectIds": [161, 172, 183]
}

### VIEW STUDENTS (HOD/ADMIN)
GET http://localhost:5000/api/admin/students
Content-Type: application/json

### MY PROFILE 
GET http://localhost:5000/api/admin/me
Content-Type: application/json


### PROFESSOR

### VIEW STUDENTS (PROFESSOR)
GET http://localhost:5000/api/professor/students
Content-Type: application/json

### MY PROFILE 
GET http://localhost:5000/api/professor/me
Content-Type: application/json


### STUDENT

### MY PROFILE 
GET http://localhost:5000/api/student/me
Content-Type: application/json


### ASSIGNMENT

### CREATE ASSIGNMENT (ADMIN / PROFESSOR)
POST http://localhost:5000/api/assignment
Content-Type: application/json

{
    "title": "Assignment – Water Treatment",
    "description": "Study of water hardness, alkalinity, and purification methods including ion exchange and reverse osmosis. Explain industrial applications with neat diagrams.",
    "dueDate": "2026-02-01",
    "subjectId": 161,
    "semesterId": 10,
    "attachment": "null"
}

### GET ASSIGNMENTS (STUDENT)
GET http://localhost:5000/api/assignment/students
Content-Type: application/json

### CHANGE ASSIGNMENT STATUS (STUNDENT)
PUT http://localhost:5000/api/assignment/1/status
Content-Type: application/json

{
  "statusId": 20
}

### ENUMS
GET http://localhost:5000/api/enums/BRANCH