export const SUBJECTS = {
  "Computer Engineering": {
    "Semester 1": [
      "Programming Fundamentals",
      "Engineering Mathematics-I",
      "Digital Logic Design",
      "Computer Organization",
      "Communication Skills",
    ],
    "Semester 2": [
      "Data Structures",
      "Engineering Mathematics-II",
      "Object Oriented Programming",
      "Environmental Studies",
      "Discrete Mathematics",
    ],
    "Semester 3": [
      "Operating Systems",
      "Database Management Systems",
      "Computer Networks",
      "Software Engineering",
      "Microprocessors",
    ],
    "Semester 4": [
      "Web Technologies",
      "Design & Analysis of Algorithms",
      "Computer Architecture",
      "Theory of Computation",
      "Professional Ethics",
    ],
    "Semester 5": [
      "Artificial Intelligence",
      "Machine Learning",
      "Data Mining",
      "Compiler Design",
      "Human-Computer Interaction",
    ],
    "Semester 6": [
      "Mobile Computing",
      "Cloud Computing",
      "Cyber Security",
      "Internet of Things",
      "Data Visualization",
    ],
    "Semester 7": [
      "Big Data Analytics",
      "Blockchain Technology",
      "Advanced DBMS",
      "Soft Computing",
      "Elective - I",
    ],
    "Semester 8": [
      "Deep Learning",
      "NLP",
      "Elective - II",
      "Project Work",
      "Internship",
    ],
  },

  "Mechanical Engineering": {
    "Semester 1": [
      "Engineering Mechanics",
      "Engineering Mathematics-I",
      "Engineering Graphics",
      "Basic Electrical Engineering",
      "Communication Skills",
    ],
    "Semester 2": [
      "Thermodynamics",
      "Engineering Mathematics-II",
      "Material Science",
      "Manufacturing Processes",
      "Environmental Studies",
    ],
    "Semester 3": [
      "Fluid Mechanics",
      "Strength of Materials",
      "Machine Drawing",
      "Applied Thermodynamics",
      "Kinematics of Machines",
    ],
    "Semester 4": [
      "Dynamics of Machines",
      "Heat Transfer",
      "Industrial Engineering",
      "Mechanical Measurements",
      "CAD/CAM",
    ],
    "Semester 5": [
      "Design of Machine Elements",
      "I.C. Engines",
      "Refrigeration & AC",
      "Mechatronics",
      "Elective - I",
    ],
    "Semester 6": [
      "Robotics",
      "Finite Element Analysis",
      "Production Planning",
      "Vibration Analysis",
      "Quality Control",
    ],
    "Semester 7": [
      "Composite Materials",
      "Renewable Energy Systems",
      "Automobile Engineering",
      "Elective - II",
      "Seminar",
    ],
    "Semester 8": [
      "Project Work",
      "Maintenance Engineering",
      "Elective - III",
      "Internship",
      "Operations Research",
    ],
  },

  "Electrical Engineering": {
    "Semester 1": [
      "Basic Electrical Engineering",
      "Engineering Mathematics-I",
      "Physics",
      "Engineering Graphics",
      "Communication Skills",
    ],
    "Semester 2": [
      "Electrical Circuit Analysis",
      "Engineering Mathematics-II",
      "Analog Electronics",
      "Digital Electronics",
      "Environmental Studies",
    ],
    "Semester 3": [
      "Electrical Machines-I",
      "Network Analysis",
      "Power Systems-I",
      "Electromagnetic Fields",
      "Control Systems",
    ],
    "Semester 4": [
      "Electrical Machines-II",
      "Microprocessors & Controllers",
      "Power Electronics",
      "Signals & Systems",
      "Electrical Measurements",
    ],
    "Semester 5": [
      "Switchgear & Protection",
      "Electrical Drives",
      "Industrial Automation",
      "Instrumentation",
      "Elective - I",
    ],
    "Semester 6": [
      "HVDC Transmission",
      "Renewable Energy",
      "Smart Grids",
      "Electric Vehicles",
      "Power Quality",
    ],
    "Semester 7": [
      "Advanced Control Systems",
      "Energy Audit",
      "Digital Signal Processing",
      "Elective - II",
      "Seminar",
    ],
    "Semester 8": [
      "Project Work",
      "Internship",
      "Electrical Safety",
      "Elective - III",
      "High Voltage Engineering",
    ],
  },

  "Civil Engineering": {
    "Semester 1": [
      "Engineering Mechanics",
      "Engineering Mathematics-I",
      "Engineering Graphics",
      "Basic Electrical Engineering",
      "Communication Skills",
    ],
    "Semester 2": [
      "Surveying",
      "Engineering Mathematics-II",
      "Building Materials",
      "Fluid Mechanics",
      "Environmental Studies",
    ],
    "Semester 3": [
      "Structural Analysis-I",
      "Concrete Technology",
      "Geotechnical Engineering",
      "Engineering Geology",
      "Transportation Engineering-I",
    ],
    "Semester 4": [
      "Structural Analysis-II",
      "Water Resources Engineering",
      "Construction Planning",
      "Soil Mechanics",
      "Transportation Engineering-II",
    ],
    "Semester 5": [
      "Design of RCC Structures",
      "Design of Steel Structures",
      "Environmental Engineering-I",
      "Estimation & Costing",
      "Elective - I",
    ],
    "Semester 6": [
      "Environmental Engineering-II",
      "Advanced Surveying",
      "Prestressed Concrete",
      "Construction Management",
      "Ground Improvement Techniques",
    ],
    "Semester 7": [
      "Earthquake Engineering",
      "GIS & Remote Sensing",
      "Traffic Engineering",
      "Elective - II",
      "Seminar",
    ],
    "Semester 8": [
      "Project Work",
      "Internship",
      "Building Services",
      "Quantity Surveying",
      "Elective - III",
    ],
  },

  "Chemical Engineering": {
    "Semester 1": [
      "Engineering Chemistry",
      "Engineering Mathematics-I",
      "Communication Skills",
      "Basics of Chemical Engineering",
      "Engineering Graphics",
    ],
    "Semester 2": [
      "Engineering Mathematics-II",
      "Environmental Studies",
      "Fluid Flow",
      "Organic Chemistry",
      "Process Calculation",
    ],
    "Semester 3": [
      "Chemical Engineering Thermodynamics",
      "Mechanical Operations",
      "Heat Transfer",
      "Instrumentation",
      "Physical Chemistry",
    ],
    "Semester 4": [
      "Mass Transfer-I",
      "Reaction Engineering-I",
      "Energy Engineering",
      "Numerical Methods",
      "Industrial Safety",
    ],
    "Semester 5": [
      "Mass Transfer-II",
      "Reaction Engineering-II",
      "Process Equipment Design",
      "Petroleum Refining",
      "Elective - I",
    ],
    "Semester 6": [
      "Biochemical Engineering",
      "Polymer Technology",
      "Process Control",
      "Plant Utilities",
      "Transport Phenomena",
    ],
    "Semester 7": [
      "Environmental Pollution Control",
      "Chemical Process Modeling",
      "Nanotechnology",
      "Elective - II",
      "Seminar",
    ],
    "Semester 8": [
      "Project Work",
      "Internship",
      "Process Optimization",
      "Chemical Plant Design",
      "Elective - III",
    ],
  },
} as const;